### ISSUE TITLE
testing 5377: change order of filters

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/a4-meinberlin#4197]
**URL:** /projekte
**user:** any
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** we changed the order of filters so that we have more space for the new one.

Design:
<img width="799" alt="Bildschirmfoto 2022-02-24 um 16 09 23" src="https://user-images.githubusercontent.com/35491681/155551062-48def00b-43d5-44c8-86ec-c8f4f1f525f9.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer I can change this but just fyi this is behaviour we implemented when first launching the filter (see prod) and I'm not sure if it might be because the organisatiobn dropdown runs into problems if it is layered over the map on small devices, I can remove it but I would advise lots of testing, will tag you when it's merged

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland oh it may be that we did it on purpose, that would explain it, but I don't remember. So for Samsung Galaxy S20 on chrome and Samsung Galaxy S6 on chrome I can say that if you click into the organisation field but then don't chose an organisation you don't see the "show projects" button. On iphones you can hide the keyboard (haven't found for android). But for both you can still get back if clicking somewhere else on the form. Is this ok from a UX perspective?
