### ISSUE TITLE
Mailings MeinBerlin

### ISSUE THREAD

**Issue by Anastasiia3040** [liqd/a4-meinberlin#5878]
important screensize: mobile and desktop
device & browser: mailbox 
Comment/Question:  The logo in header and footer in Mailbox the logos are missing. And the mail is received with the attached logo files. Would that be possible to fix this? 

![Screenshot 2024-12-11 at 14 04 37](https://github.com/user-attachments/assets/d8866161-d1a9-4714-9846-220a9af7fb13)

**Comment by Anastasiia3040** [comment]
@philli-m there's also the problem with the button on Gmail. And with the logos as well 
![Screenshot 2024-12-11 at 14 42 59](https://github.com/user-attachments/assets/497305d9-c4bb-44e6-b8f1-9e87677dc30a)

**Comment by CarolingerSeilchenspringer** [comment]
I think we mean @vellip here, with best greetings to @philli-m who is out of duty :-)

**Comment by Anastasiia3040** [comment]
I got another Mail and the button looks different there as well. It is on gmail(both mobile and desktop). Is it possible to fix this? 
<img width="703" alt="Screenshot 2024-12-12 at 16 01 59" src="https://github.com/user-attachments/assets/b31bb826-0ca6-4ea1-805a-8d8dcec892fb" />

**Comment by sblindow** [comment]
There is an issue in the "Moderationsaufgabe"/ "Gemeldeter Beitrag" E-Mail in which the images for the button and the berlin.de logo are missing, even in clients that work with all other E-Mails. 
<img width="832" alt="Bildschirmfoto 2024-12-12 um 17 22 00" src="https://github.com/user-attachments/assets/d719f1ac-1b96-49e3-9ec2-47e34dc60a95" />

**Comment by sblindow** [comment]
In the "Neues Projekt" E-Mail the Button is too close to the text (in all clients/ systems)

<img width="838" alt="Bildschirmfoto 2024-12-12 um 17 25 03" src="https://github.com/user-attachments/assets/87fd37ba-5261-49f8-a971-33418a7329fd" />

**Comment by sblindow** [comment]
Other configurations that don't load the images are: 
1. Apple Mail App IOS
![mail-app_IOS](https://github.com/user-attachments/assets/04880094-933a-4015-a921-a5fb31701aa4)

2. Outlook App IOS
![outlook-ios](https://github.com/user-attachments/assets/129ce262-0ac6-4393-8e41-106dcb34316d)

3. Gmail App IOS
![gmail-app_ios](https://github.com/user-attachments/assets/d3c1e7b2-a16c-434e-8b7f-f6b9009f5a1f)

4. Outlook App Android
![outlook-app_android](https://github.com/user-attachments/assets/9626a805-d1db-4950-b92c-1074bb0fbe3d)

5. Gmail App Android
![gmail-app_android](https://github.com/user-attachments/assets/0deb87b1-19fb-4cf6-ae3d-5a219841164f)

**Comment by sblindow** [comment]
In Apple Mail on IOS there is a strange behavior when clicking the button on the green arrow image part. The browser opens correctly, but when you switch back to the mail app, a detail view of the green arrow image is open. You can find a screenrecording in taiga (could't upload .mp4 to github)

**Comment by vellip** [comment]
Maybe you can re-test this, as I have deployed some changes this week

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow can you test again?

**Comment by sblindow** [comment]
@vellip @CarolingerSeilchenspringer I tested most of the Platforms and Clients except yahoo and the Outlook Mobile app (it didn't load may e-mails for some reason). 
Here are the issues that I found: 
1. "mein.berlin.de" Logo is not loading on all platforms/ clients that I tested
2. Mailbox still shows the logo image files as attachments
3. Gmail IOS App has multiple Issues: 
	- logos and buttons do not have images
	- email width does not respond to the smaller screen
	- strange text in the footer (see screenshot)
4. Gmail Android App: logos and buttons do not work either
5. The Platform Mail still contains an empty button that shouldn't be there (Maybe there are two different platform mails? Because you can either send them from the burger menu/ sidebar or from the initiator menu (both as an admin))

![Image](https://github.com/user-attachments/assets/904de2cd-0a1b-4bd8-bc14-014d872db32c)

**Comment by vellip** [comment]
definitely a rabbit hole yes

**Comment by CarolingerSeilchenspringer** [comment]
I want to add Win10, MS Outlook 2021, HP Elitebook to this. We got feedback from Skzl that the mail button was broken.

**Comment by vellip** [comment]
@CarolingerSeilchenspringer regarding all the missing images: we currently have four images:

- the berlin logo in the header
- mein berlin logo
- the arrow icon in the button
- the berlin logo in the footer

these four won't load until the user clicks "show images" in their mail client. until this happens the emails basically look like they do in the screenshots.

I am using the same technique that has been used the years before when implementing images in mails. If you want images to always load without the user having to allow it, we would need to rethink how we do images in emails. 

Currently we send the images as attachments to the mail, the alternative would be to "host" the images on the respective server (demo server for demo emails) and then link to those images. So instead of a link to an attachment, we have a link like https://demo-server.de/static/berlin-header-logo.png. I can't speak as to why this hasn't been done before. I know it's going to increase traffic towards the servers, but I am not sure if this is a legit concern or maybe doesn't matter for a server that should be able to handle tons of requests. cc @goapunk

**Comment by goapunk** [comment]
@vellip all the images are already available on the server, e.g. email_logo.e3bfe683aecb.png. I don't see an immediate reason not use them if the current way poses a big problem. You'd need to get the url with {% static '' %} in the email template

**Comment by t-j-q** [comment]
#6432 maybe linked

**Comment by CarolingerSeilchenspringer** [comment]
@sblindow can you please test again? I meanwhile put the issue on hold so @partizipation can continue with other issues.
